[2025-05-06T10:51:25.119+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-06T10:51:25.186+0000] {taskinstance.py:2066} INFO - Dependencies not met for <TaskInstance: test_mysql_connection.query_mysql manual__2025-05-06T10:51:26.672296+00:00 [queued]>, dependency 'Execution Date' FAILED: Execution date 2025-05-06T10:51:26.672296+00:00 is in the future (the current date is 2025-05-06T10:51:25.185953+00:00).
[2025-05-06T10:51:25.197+0000] {local_task_job_runner.py:163} INFO - Task is not able to be run
