[2025-05-08T14:59:35.621+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-08T14:59:35.691+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl_decorator.transform.transform_fact_orders manual__2025-05-08T14:58:40.551626+00:00 [queued]>
[2025-05-08T14:59:35.705+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl_decorator.transform.transform_fact_orders manual__2025-05-08T14:58:40.551626+00:00 [queued]>
[2025-05-08T14:59:35.709+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-05-08T14:59:35.738+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_fact_orders> on 2025-05-08 14:58:40.551626+00:00
[2025-05-08T14:59:35.756+0000] {standard_task_runner.py:63} INFO - Started process 10825 to run task
[2025-05-08T14:59:35.763+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl_decorator', 'transform.transform_fact_orders', 'manual__2025-05-08T14:58:40.551626+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_dw_dag.py', '--cfg-path', '/tmp/tmpmc2soynv']
[2025-05-08T14:59:35.767+0000] {standard_task_runner.py:91} INFO - Job 116: Subtask transform.transform_fact_orders
[2025-05-08T14:59:35.862+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl_decorator.transform.transform_fact_orders manual__2025-05-08T14:58:40.551626+00:00 [running]> on host ebff8b55cad8
[2025-05-08T14:59:36.136+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl_decorator' AIRFLOW_CTX_TASK_ID='transform.transform_fact_orders' AIRFLOW_CTX_EXECUTION_DATE='2025-05-08T14:58:40.551626+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-08T14:58:40.551626+00:00'
[2025-05-08T14:59:36.139+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-08T14:59:36.166+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-05-08T14:59:36.188+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-05-08T14:59:36.969+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-05-08T14:59:36.976+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-05-08T14:59:37.434+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-05-08T14:59:37.440+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-05-08T14:59:37.790+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-05-08T14:59:37.798+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-05-08T14:59:38.660+0000] {logging_mixin.py:188} INFO - The columns of dataframe after merged: Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date',
       'price', 'freight_value', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value', 'customer_zip_code_prefix'],
      dtype='object')
[2025-05-08T14:59:39.677+0000] {logging_mixin.py:188} INFO - Transformed and saved data to fact_orders
[2025-05-08T14:59:39.804+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-05-08T14:59:39.805+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-08T14:59:39.819+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=e_commerce_dw_etl_decorator, task_id=transform.transform_fact_orders, run_id=manual__2025-05-08T14:58:40.551626+00:00, execution_date=20250508T145840, start_date=20250508T145935, end_date=20250508T145939
[2025-05-08T14:59:39.906+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-08T14:59:39.938+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-08T14:59:39.941+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
