[2025-05-09T07:07:47.830+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-09T07:07:47.900+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl_decorator.load.load_fact_orders scheduled__2025-05-08T00:00:00+00:00 [queued]>
[2025-05-09T07:07:47.916+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl_decorator.load.load_fact_orders scheduled__2025-05-08T00:00:00+00:00 [queued]>
[2025-05-09T07:07:47.918+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-05-09T07:07:47.947+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load.load_fact_orders> on 2025-05-08 00:00:00+00:00
[2025-05-09T07:07:47.958+0000] {standard_task_runner.py:63} INFO - Started process 342 to run task
[2025-05-09T07:07:47.963+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl_decorator', 'load.load_fact_orders', 'scheduled__2025-05-08T00:00:00+00:00', '--job-id', '178', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_dw_dag.py', '--cfg-path', '/tmp/tmp_2lrx7ck']
[2025-05-09T07:07:47.967+0000] {standard_task_runner.py:91} INFO - Job 178: Subtask load.load_fact_orders
[2025-05-09T07:07:48.046+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl_decorator.load.load_fact_orders scheduled__2025-05-08T00:00:00+00:00 [running]> on host 335a73e8cf0f
[2025-05-09T07:07:48.244+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl_decorator' AIRFLOW_CTX_TASK_ID='load.load_fact_orders' AIRFLOW_CTX_EXECUTION_DATE='2025-05-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-08T00:00:00+00:00'
[2025-05-09T07:07:48.245+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-09T07:07:48.248+0000] {logging_mixin.py:188} INFO - Loading latest file: /tmp/fact_orders_09May2025.parquet
[2025-05-09T07:07:49.022+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-05-09T07:08:13.938+0000] {logging_mixin.py:188} INFO - Loaded data to fact_orders successfully.
[2025-05-09T07:08:13.959+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-05-09T07:08:13.961+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-09T07:08:13.977+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=e_commerce_dw_etl_decorator, task_id=load.load_fact_orders, run_id=scheduled__2025-05-08T00:00:00+00:00, execution_date=20250508T000000, start_date=20250509T070747, end_date=20250509T070813
[2025-05-09T07:08:14.069+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-09T07:08:14.088+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-09T07:08:14.091+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
